# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Grafana installation tasks
  tags:
    - setup-all
    - setup-grafana
    - install-all
    - install-grafana
  block:
    - name: Validate Grafana configuration
      when: grafana_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Grafana
      when: grafana_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Grafana uninstallation tasks
  tags:
    - setup-all
    - setup-grafana
  block:
    - name: Uninstall Grafana
      when: not grafana_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
