# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Grafana systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ grafana_identifier }}.service"
  register: grafana_service_stat

- when: grafana_service_stat.stat.exists | bool
  block:
    - name: Ensure Grafana systemd service is stopped
      ansible.builtin.service:
        name: "{{ grafana_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Grafana systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ grafana_identifier }}.service"
        state: absent

    - name: Ensure Grafana path does not exist
      ansible.builtin.file:
        path: "{{ grafana_base_path }}"
        state: absent
